// Generated by scripts/gen_icons.py from the Icon:: identifiers
// used in src/. Do not edit by hand; reference an icon in code and
// regenerate. Run scripts/gen_icons.py --search to find one.
#pragma once
#include <Arduino.h>

// Changing the referenced icons or a vendored SVG changes this
// value; CI compares it so generated data cannot go stale.
#define DESKMATE_ICON_DIGEST "d42d04167d1cde7f"

enum class Icon : uint8_t {
  Activity,  // lucide:activity @16px
  AtSign,  // lucide:at-sign @16px
  CircleCheck,  // lucide:circle-check @16px
  CircleCheck14,  // lucide:circle-check @14px
  CircleCheck24,  // lucide:circle-check @24px
  CircleDot,  // lucide:circle-dot @16px
  CircleSmall14,  // lucide:circle-small @14px
  CircleX14,  // lucide:circle-x @14px
  Flame14,  // lucide:flame @14px
  GitCommitHorizontal,  // lucide:git-commit-horizontal @16px
  GitGraph,  // lucide:git-graph @16px
  GitMerge,  // lucide:git-merge @16px
  GitPullRequest,  // lucide:git-pull-request @16px
  GitPullRequestClosed,  // lucide:git-pull-request-closed @16px
  GitPullRequestDraft,  // lucide:git-pull-request-draft @16px
  Inbox,  // lucide:inbox @16px
  MessageSquareCode,  // lucide:message-square-code @16px
  Plane12,  // lucide:plane @12px, 24 rotations
  Plane16,  // lucide:plane @16px, 24 rotations
  Count
};

constexpr uint8_t kIconCount = static_cast<uint8_t>(Icon::Count);

// Every glyph, concatenated. 1 bpp, MSB first, each row
// padded to a byte -- the layout drawBitmap() expects.
extern const uint8_t kIconBits[] PROGMEM;

// Five bytes per icon: offset high, offset low, width,
// height, and the number of evenly spaced rotation frames
// stored back to back at that offset (1 when the glyph does
// not point anywhere).
constexpr uint8_t kIconMetaStride = 5;
extern const uint8_t kIconMeta[kIconCount * kIconMetaStride] PROGMEM;
