#include "GithubMode.h"
#include "Platform.h"
#include "Gfx.h"
#include "TileRenderer.h"
#include <ArduinoJson.h>
#include <Arduino_GFX_Library.h>
GithubMode g_githubMode;
struct GHData{bool valid=false,error=false;char repo[48]="";char sha[8]="";char msg[64]="";int issues=0,prs=0;uint8_t activity[35]={0};uint32_t updated=0;}static G;
static bool getJson(const Settings&s,const String&url,JsonDocument&d){std::unique_ptr<SecureClient>c(platformMakeSecureClient(4096,nullptr,512,false));HTTPClient h;h.setTimeout(s.httpTimeout);if(!h.begin(*c,url))return false;h.addHeader("User-Agent",FW_NAME);h.addHeader("Accept","application/vnd.github+json");h.addHeader("X-GitHub-Api-Version","2022-11-28");if(s.github.token.length())h.addHeader("Authorization","Bearer "+s.github.token);int rc=h.GET();if(rc!=200){h.end();return false;}String payload=h.getString();h.end();auto e=deserializeJson(d,payload);return !e;}
static int searchCount(const Settings&s,const String&q){JsonDocument d;if(!getJson(s,"https://api.github.com/search/issues?per_page=1&q="+q,d))return -1;return d["total_count"]|-1;}
void GithubMode::fetch(const Settings&s){if(!s.github.repoCount){G.error=true;dirty_=true;return;}String repo=s.github.repos[0].repo;strlcpy(G.repo,repo.c_str(),sizeof(G.repo));JsonDocument d;if(!getJson(s,"https://api.github.com/repos/"+repo+"/commits?per_page=1",d)){G.error=true;dirty_=true;return;}JsonObjectConst c=d[0];String sha=c["sha"]|"";strlcpy(G.sha,sha.substring(0,7).c_str(),sizeof(G.sha));String m=c["commit"]["message"]|"";int nl=m.indexOf('\n');if(nl>=0)m=m.substring(0,nl);strlcpy(G.msg,m.c_str(),sizeof(G.msg));int pr=searchCount(s,"repo:"+repo+"+is:pr+is:open");int all=searchCount(s,"repo:"+repo+"+is:issue+is:open");G.prs=max(0,pr);G.issues=max(0,all);JsonDocument act; if(getJson(s,"https://api.github.com/repos/"+repo+"/stats/commit_activity",act)){ JsonArrayConst weeks=act.as<JsonArrayConst>(); int wc=weeks.size(); int out=0; for(int wi=max(0,wc-5);wi<wc&&out<35;wi++){ JsonArrayConst days=weeks[wi]["days"].as<JsonArrayConst>(); for(JsonVariantConst v:days){ if(out<35)G.activity[out++]=(uint8_t)constrain(v.as<int>(),0,4); } } while(out<35)G.activity[out++]=0; } G.valid=true;G.error=false;G.updated=millis();dirty_=true;}
static void drawGH(TileCanvas&g,void*){g.fillScreen(C_BLACK);g.setTextWrap(false);g.setTextSize(1);g.setTextColor(C_GRAY);g.setCursor(8,8);g.print("GITHUB STATUS");if(!G.valid){g.setTextSize(2);g.setTextColor(G.error?C_RED:C_YELLOW);g.setCursor(34,108);g.print(G.error?"CONFIG / API ERROR":"LOADING");return;}g.setTextSize(2);g.setTextColor(C_WHITE);g.setCursor(8,32);String rn=G.repo;int slash=rn.indexOf('/');if(slash>=0)rn=rn.substring(slash+1);g.print(rn.substring(0,18));g.setTextSize(1);g.setTextColor(C_GREEN);g.setCursor(8,59);g.print(G.sha);g.setTextColor(C_GRAY);g.setCursor(58,59);g.print("latest commit");g.setTextColor(C_WHITE);String msg=G.msg;g.setCursor(8,78);g.print(msg.substring(0,36));if(msg.length()>36){g.setCursor(8,90);g.print(msg.substring(36,72));}
  g.drawRoundRect(8,112,106,40,6,C_DGRAY);g.drawRoundRect(126,112,106,40,6,C_DGRAY);g.setTextSize(2);g.setTextColor(C_YELLOW);g.setCursor(18,122);g.print(G.issues);g.setTextSize(1);g.setTextColor(C_GRAY);g.setCursor(52,129);g.print("ISSUES");g.setTextSize(2);g.setTextColor(C_BLUE);g.setCursor(136,122);g.print(G.prs);g.setTextSize(1);g.setTextColor(C_GRAY);g.setCursor(170,129);g.print("OPEN PR");
  g.setCursor(8,166);g.print("COMMIT PULSE");for(int i=0;i<35;i++){int x=8+(i%7)*16,y=184+(i/7)*10;uint16_t c=G.activity[i]==0?C_DGRAY:G.activity[i]<2?0x0320:G.activity[i]<4?C_GREEN:0x07FF;g.fillRoundRect(x,y,11,7,2,c);} }
void GithubMode::begin(const Settings&){next_=0;dirty_=true;}void GithubMode::invalidate(const Settings&){next_=0;dirty_=true;}void GithubMode::wake(const Settings&){dirty_=true;}void GithubMode::render(const Settings&s){gfxRenderTiled(drawGH,nullptr,C_BLACK);}void GithubMode::service(const Settings&s){uint32_t n=millis();if((int32_t)(n-next_)>=0){next_=n+(uint32_t)s.github.pollSec*1000;fetch(s);}if(dirty_){render(s);dirty_=false;}}
