#!/usr/bin/env python3
"""Generate src/display/IconData.{h,cpp} from the icons the firmware uses.

There is no list of icons to maintain. Firmware code writes
`gfxDrawIcon(canvas, Icon::CodeMerge, x, y, color)`; this script scans src/ for
those identifiers, resolves each against the committed pack catalogs, downloads
any SVG not yet vendored, and emits exactly the glyphs that are referenced. An
icon that stops being used stops being compiled in.

    python3 scripts/gen_icons.py                regenerate from current usage
    python3 scripts/gen_icons.py --preview      also print an ASCII proof sheet
    python3 scripts/gen_icons.py --list         show what is compiled in
    python3 scripts/gen_icons.py --search pull  find an icon across all packs
    python3 scripts/gen_icons.py --check        exit 1 if the sources are stale
    python3 scripts/gen_icons.py --from DIR     vendor from a local package

Identifier rules:
  * PascalCase maps to the pack's own name -- `CodePullRequest` is
    `code-pull-request`.
  * A trailing number is the render size in pixels, default 16. `DotFill12`
    and `DotFill24` are the same drawing at two sizes; neither needs declaring.
  * Ambiguities and per-glyph threshold tweaks go in assets/icons.overrides.

--check compares a digest of the resolved icon set and the vendored SVG bytes
against the value recorded in IconData.h. It deliberately does not re-rasterize:
librsvg builds disagree on a boundary pixel, and comparing bitmaps would report
that as drift. So --check needs neither Pillow nor a rasterizer.
"""
import hashlib
import math
import os
import re
import xml.etree.ElementTree as ElementTree
import shutil
import subprocess
import sys
import tempfile
import urllib.request

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import icon_index as index

SRC_DIR = os.path.join(index.ROOT, "src")
OUT_DIR = os.path.join(index.ROOT, "src", "display")
HEADER = os.path.join(OUT_DIR, "IconData.h")
SOURCE = os.path.join(OUT_DIR, "IconData.cpp")
GENERATED = {"IconData.h", "IconData.cpp"}
BANNER = ("// Generated by scripts/gen_icons.py from the Icon:: identifiers\n"
          "// used in src/. Do not edit by hand; reference an icon in code and\n"
          "// regenerate. Run scripts/gen_icons.py --search to find one.\n")

# Bump when the rasterization rules change, so --check treats bitmaps built by
# an older generator as stale even if no source moved. v2 centers a non-square
# glyph in its box instead of stretching it; v3 derives the set from usage.
FORMAT_VERSION = 3

USAGE = re.compile(r"\bIcon::([A-Za-z][A-Za-z0-9]*)\b")
RESERVED = {"Count"}

# Comments discuss icons -- the header documents Icon::DotFill12 as an example
# -- so they are blanked before scanning. Newlines are preserved so reported
# line numbers still point at the real reference. Being naive about string
# literals can only lose a reference, never invent one, and a lost reference
# shows up immediately as a compile error against the generated enum.
BLOCK_COMMENT = re.compile(r"/\*.*?\*/", re.DOTALL)
LINE_COMMENT = re.compile(r"//[^\n]*")


def strip_comments(text):
    text = BLOCK_COMMENT.sub(lambda m: "\n" * m.group(0).count("\n"), text)
    return LINE_COMMENT.sub("", text)


# --- discovering what the firmware uses ------------------------------------
def scan_usage():
    """Every `Icon::Name` referenced in src/ code, with one example location."""
    found = {}
    for base, _, files in os.walk(SRC_DIR):
        for filename in sorted(files):
            if not filename.endswith((".h", ".cpp")) or filename in GENERATED:
                continue
            path = os.path.join(base, filename)
            with open(path, encoding="utf-8", errors="replace") as handle:
                code = strip_comments(handle.read())
            for lineno, line in enumerate(code.split("\n"), 1):
                for name in USAGE.findall(line):
                    if name in RESERVED or name in found:
                        continue
                    found[name] = "%s:%d" % (
                        os.path.relpath(path, index.ROOT), lineno)
    return found


def resolve_all(usage, catalogs, overrides):
    resolved, problems = [], []
    for identifier in sorted(usage):
        icon, error = index.resolve(identifier, catalogs, overrides)
        if error:
            problems.append("%s: %s" % (usage[identifier], error))
        else:
            resolved.append(icon)
    if problems:
        sys.exit("unresolved icon reference(s):\n  " + "\n  ".join(problems))
    return resolved


def vendor(icons, sources):
    """Copy in any referenced SVG that is not vendored yet.

    A local release package registered in assets/icons/sources.conf is
    preferred, so a machine holding one never needs the network; otherwise the
    glyph is downloaded from the pack's repository.
    """
    missing = [icon for icon in icons if not os.path.exists(icon.svg)]
    for icon in missing:
        os.makedirs(os.path.dirname(icon.svg), exist_ok=True)
        local = index.local_svg(icon.pack, icon.path, sources)
        if local:
            with open(local, "rb") as handle:
                body = handle.read()
            origin = "local"
        else:
            try:
                with urllib.request.urlopen(icon.url, timeout=30) as response:
                    body = response.read()
            except Exception as error:  # noqa: BLE001
                sys.exit("%s: cannot obtain %s\n  %s\n  %s"
                         % (icon.identifier, icon.pack, error, icon.url))
            origin = "download"
        if b"<svg" not in body:
            sys.exit("%s: %s is not an SVG" % (icon.identifier, local or icon.url))
        with open(icon.svg, "wb") as handle:
            handle.write(body)
        print("vendored %-24s %s:%s  (%s)"
              % (icon.identifier, icon.pack, icon.path, origin))
    return len(missing)


# --- rasterization ---------------------------------------------------------
def _render_rsvg(svg, size, png):
    subprocess.run(["rsvg-convert", "-w", str(size), "-h", str(size),
                    "-o", png, svg], check=True, capture_output=True)


def _render_magick(svg, size, png):
    subprocess.run(["magick", "-background", "none", "-size",
                    "%dx%d" % (size, size), svg, "png32:" + png],
                   check=True, capture_output=True)


def _render_cairosvg(svg, size, png):
    import cairosvg
    cairosvg.svg2png(url=svg, write_to=png,
                     output_width=size, output_height=size)


def pick_backend():
    if shutil.which("rsvg-convert"):
        return "rsvg-convert", _render_rsvg
    try:
        import cairosvg  # noqa: F401
        return "cairosvg", _render_cairosvg
    except ImportError:
        pass
    if shutil.which("magick"):
        return "magick", _render_magick
    sys.exit("no SVG rasterizer found; install librsvg2-tools, cairosvg, "
             "or ImageMagick")


VIEWBOX = re.compile(r'viewBox="([-\d.eE]+(?:\s+[-\d.eE]+){3})"')


def rotated_source(icon, degrees, workdir):
    """A copy of the glyph's SVG with its drawing rotated about its centre."""
    if not degrees:
        return icon.svg
    source = open(icon.svg, encoding="utf-8").read()
    found = VIEWBOX.search(source)
    if not found:
        sys.exit("%s: %s has no viewBox, so it cannot be rotated"
                 % (icon.identifier, os.path.relpath(icon.svg, index.ROOT)))
    x, y, w, h = (float(v) for v in found.group(1).split())
    body = source[source.index(">", source.index("<svg")) + 1:
                  source.rindex("</svg>")]
    path = os.path.join(workdir, "%s-%d.svg" % (icon.identifier, int(degrees)))
    with open(path, "w", encoding="utf-8") as handle:
        handle.write('<svg xmlns="http://www.w3.org/2000/svg" '
                     'viewBox="%s %s %s %s">'
                     '<g transform="rotate(%s %s %s)">%s</g></svg>'
                     % (x, y, w, h, degrees, x + w / 2, y + h / 2, body))
    return path


def rasterize(icon, render, workdir, degrees=0.0):
    from PIL import Image
    png = os.path.join(workdir, "%s-%d.png" % (icon.identifier, int(degrees)))
    render(rotated_source(icon, degrees, workdir), icon.size, png)
    rendered = Image.open(png).convert("RGBA")

    # Packs do not agree on aspect ratio. Octicons draws on a square grid, but
    # FontAwesome uses a 512-tall grid with a per-icon width, so a glyph comes
    # back short or narrow. Center it in the box rather than scaling it to fit:
    # stretching to square distorts the drawing (a 640x512 glyph would be
    # pulled 33% taller).
    image = Image.new("RGBA", (icon.size, icon.size), (0, 0, 0, 0))
    if rendered.size != (icon.size, icon.size):
        if rendered.size[0] > icon.size or rendered.size[1] > icon.size:
            rendered.thumbnail((icon.size, icon.size), Image.LANCZOS)
        image.paste(rendered, ((icon.size - rendered.size[0]) // 2,
                               (icon.size - rendered.size[1]) // 2))
    else:
        image = rendered

    # A glyph is opaque paint on a transparent ground, so alpha is coverage.
    # Cutting below 50% keeps hairlines that a naive 50% threshold erases.
    pixels = image.split()[3].load()
    rows = [[1 if pixels[x, y] >= icon.threshold else 0
             for x in range(icon.size)] for y in range(icon.size)]
    if not any(any(row) for row in rows):
        sys.exit("%s rasterized empty at %dpx; lower its threshold in "
                 "assets/icons.overrides" % (icon.identifier, icon.size))
    return rows


def nose_bearing(rows):
    """Compass bearing of the point furthest from a glyph's centre of mass."""
    ink = [(x, y) for y, row in enumerate(rows)
           for x, bit in enumerate(row) if bit]
    if not ink:
        return None
    cx = sum(p[0] for p in ink) / len(ink)
    cy = sum(p[1] for p in ink) / len(ink)
    nose = max(ink, key=lambda p: (p[0] - cx) ** 2 + (p[1] - cy) ** 2)
    return math.degrees(math.atan2(nose[0] - cx, -(nose[1] - cy))) % 360


def check_points_north(icon, rows):
    """Frame 0 of a rotating glyph must point north, or every heading is off.

    Packs draw a vehicle at whatever angle suits a toolbar -- Lucide's plane
    flies northeast -- and nothing about the drawing announces it. Measuring
    the first frame here turns a silently wrong compass into a build failure.
    """
    bearing = nose_bearing(rows)
    if bearing is None:
        return
    error = min(bearing, 360.0 - bearing)
    # Generous: the nose estimate is quantized by the raster, and a glyph is
    # not always a clean arrow. This catches a wrong base, not a stray pixel.
    if error > 20.0:
        sys.exit("%s: frame 0 points %.0f degrees from north, so every "
                 "heading would be drawn wrong.\nSet base=%.0f for it in "
                 "assets/icons.overrides (currently base=%g)."
                 % (icon.identifier, error,
                    icon.base - bearing, icon.base))


def pack_bits(rows, width):
    stride = (width + 7) // 8
    data = bytearray()
    for row in rows:
        line = bytearray(stride)
        for x, bit in enumerate(row):
            if bit:
                line[x >> 3] |= 0x80 >> (x & 7)
        data += line
    return bytes(data)


# --- code generation -------------------------------------------------------
def digest_of(icons):
    digest = hashlib.sha256()
    digest.update(b"format=%d\n" % FORMAT_VERSION)
    for icon in icons:
        digest.update(("%s|%s|%s|%d|%d|%d|%g\n"
                       % (icon.identifier, icon.pack, icon.path, icon.size,
                          icon.threshold, icon.rotations,
                          icon.base)).encode("utf-8"))
        if not os.path.exists(icon.svg):
            sys.exit("%s: %s is not vendored; run python3 scripts/gen_icons.py"
                     % (icon.identifier, os.path.relpath(icon.svg, index.ROOT)))
        with open(icon.svg, "rb") as handle:
            digest.update(handle.read())
    return digest.hexdigest()[:16]


def render_header(icons, value):
    out = [BANNER, "#pragma once\n#include <Arduino.h>\n\n",
           "// Changing the referenced icons or a vendored SVG changes this\n"
           "// value; CI compares it so generated data cannot go stale.\n",
           '#define DESKMATE_ICON_DIGEST "%s"\n\n' % value,
           "enum class Icon : uint8_t {\n"]
    for icon in icons:
        out.append("  %s,  // %s:%s @%dpx%s\n"
                   % (icon.identifier, icon.pack, icon.path, icon.size,
                      ", %d rotations" % icon.rotations
                      if icon.rotations > 1 else ""))
    out.append("  Count\n};\n\n")
    out.append("constexpr uint8_t kIconCount = "
               "static_cast<uint8_t>(Icon::Count);\n\n")
    out.append("// Every glyph, concatenated. 1 bpp, MSB first, each row\n"
               "// padded to a byte -- the layout drawBitmap() expects.\n")
    out.append("extern const uint8_t kIconBits[] PROGMEM;\n\n")
    out.append("// Five bytes per icon: offset high, offset low, width,\n"
               "// height, and the number of evenly spaced rotation frames\n"
               "// stored back to back at that offset (1 when the glyph does\n"
               "// not point anywhere).\n")
    out.append("constexpr uint8_t kIconMetaStride = 5;\n")
    out.append("extern const uint8_t kIconMeta[kIconCount * kIconMetaStride] "
               "PROGMEM;\n")
    return "".join(out)


def render_source(icons, blobs, offsets, value):
    out = [BANNER, '#include "IconData.h"\n\n',
           "const uint8_t kIconBits[] PROGMEM = {\n"]
    for icon, blob in zip(icons, blobs):
        stride = (icon.size + 7) // 8
        out.append("  // %s -- %s:%s, %dx%d, %d frame(s), %d bytes\n"
                   % (icon.identifier, icon.pack, icon.path, icon.size,
                      icon.size, icon.rotations, len(blob)))
        for start in range(0, len(blob), stride):
            chunk = blob[start:start + stride]
            out.append("  " + " ".join("0x%02X," % b for b in chunk) + "\n")
    out.append("};\n\n")
    out.append("const uint8_t kIconMeta[kIconCount * kIconMetaStride] "
               "PROGMEM = {\n")
    for icon, offset in zip(icons, offsets):
        out.append("  0x%02X, 0x%02X, %2d, %2d, %2d,  // %s\n"
                   % ((offset >> 8) & 0xFF, offset & 0xFF, icon.size,
                      icon.size, icon.rotations, icon.identifier))
    out.append("};\n")
    out.append('\nstatic_assert(sizeof(DESKMATE_ICON_DIGEST) == 17,\n'
               '              "icon digest must be 16 hex characters");\n')
    return "".join(out)


def recorded_digest():
    if not os.path.exists(HEADER):
        return None
    with open(HEADER, encoding="utf-8") as handle:
        found = re.search(r'#define DESKMATE_ICON_DIGEST "([0-9a-f]+)"',
                          handle.read())
    return found.group(1) if found else None


# --- commands --------------------------------------------------------------
def command_search(terms, catalogs):
    hits = index.search(terms, catalogs)
    if not hits:
        print("no icon matches %r" % " ".join(terms))
        return
    print("%-26s %-13s %-12s %s" % ("write in code", "pack", "variants",
                                    "keywords"))
    for _, pack, entry in hits:
        variants = ",".join(str(v) for v in entry.variants) or "-"
        # A pack outside the resolution order needs an overrides line to use.
        mark = pack if pack in index.PACK_ORDER else pack + " *"
        print("Icon::%-20s %-13s %-12s %s"
              % (index.to_identifier(entry.name), mark, variants,
                 entry.keywords))
    if any(p not in index.PACK_ORDER for _, p, _ in hits):
        print("\n* not in the default resolution order; pin it with a line in "
              "assets/icons.overrides")
    print("\nAppend a size for a smaller or larger draw, e.g. "
          "Icon::%s12" % index.to_identifier(hits[0][2].name))


def command_list(icons):
    print("%-26s %-13s %-28s %-6s %s"
          % ("identifier", "pack", "path", "size", "frames"))
    for icon in icons:
        print("Icon::%-20s %-13s %-28s %-6s %d"
              % (icon.identifier, icon.pack, icon.path,
                 "%dpx" % icon.size, icon.rotations))
    print("%d icon(s) compiled in" % len(icons))


def command_preview(icons, render):
    with tempfile.TemporaryDirectory() as workdir:
        for icon in icons:
            rows = rasterize(icon, render, workdir, icon.base)
            print("\nIcon::%s  (%s:%s, %dpx, threshold %d%s)"
                  % (icon.identifier, icon.pack, icon.path, icon.size,
                     icon.threshold,
                     ", frame 0 of %d rotations" % icon.rotations
                     if icon.rotations > 1 else ""))
            for row in rows:
                print("  " + "".join("#" if bit else "." for bit in row))


def main():
    args = sys.argv[1:]
    if "--from" in args:
        position = args.index("--from")
        if position + 1 >= len(args):
            sys.exit("usage: gen_icons.py --from DIR")
        root = os.path.abspath(os.path.expanduser(args[position + 1]))
        del args[position:position + 2]
        if not os.path.isdir(root):
            sys.exit("%s is not a directory" % root)
        for pack, spec in index.PACKS.items():
            template = spec.get("local_svg")
            if not template:
                continue
            probe = os.path.dirname(template.format(path="x/y"))
            if os.path.isdir(os.path.join(root, probe)):
                index.save_source(pack, root)
                print("registered %s package: %s" % (pack, root))

    catalogs = index.load_indexes()

    if "--search" in args:
        terms = args[args.index("--search") + 1:]
        if not terms:
            sys.exit("usage: gen_icons.py --search TERM [TERM...]")
        command_search(terms, catalogs)
        return

    usage = scan_usage()
    if not usage:
        sys.exit("no Icon:: references found under src/")
    icons = resolve_all(usage, catalogs, index.load_overrides())

    if "--check" in args:
        for path in (HEADER, SOURCE):
            if not os.path.exists(path):
                sys.exit("%s is missing; run python3 scripts/gen_icons.py"
                         % os.path.relpath(path, index.ROOT))
        want = digest_of(icons)
        have = recorded_digest()
        if have != want:
            sys.exit("src/display/IconData.h records icon digest %s but the "
                     "%d icons used in src/ hash to %s;\nrun python3 "
                     "scripts/gen_icons.py and commit the result"
                     % (have or "(none)", len(icons), want))
        print("icon data is up to date (%s, %d icons)" % (want, len(icons)))
        return

    if "--list" in args:
        command_list(icons)
        return

    vendored = vendor(icons, index.load_sources())
    name, render = pick_backend()
    print("rasterizing %d icon(s) used in src/ with %s%s"
          % (len(icons), name,
             " (%d newly vendored)" % vendored if vendored else ""))

    blobs, offsets, cursor = [], [], 0
    with tempfile.TemporaryDirectory() as workdir:
        for icon in icons:
            frames = b""
            for frame in range(icon.rotations):
                degrees = icon.base + 360.0 * frame / icon.rotations
                rows = rasterize(icon, render, workdir, degrees)
                if icon.rotations > 1 and frame == 0:
                    check_points_north(icon, rows)
                frames += pack_bits(rows, icon.size)
            blobs.append(frames)
            offsets.append(cursor)
            cursor += len(frames)
    if cursor > 0xFFFF:
        sys.exit("icon data exceeds the 64 KB offset table")

    value = digest_of(icons)
    os.makedirs(OUT_DIR, exist_ok=True)
    for path, text in ((HEADER, render_header(icons, value)),
                       (SOURCE, render_source(icons, blobs, offsets, value))):
        with open(path, "w", encoding="utf-8") as handle:
            handle.write(text)
    print("wrote %s and %s -- %d bytes of glyph data, digest %s"
          % (os.path.relpath(HEADER, index.ROOT),
             os.path.relpath(SOURCE, index.ROOT), cursor, value))

    if "--preview" in args:
        command_preview(icons, render)


if __name__ == "__main__":
    main()
