#pragma once
#include <Arduino.h>
static const char WEBUI_HTML[] PROGMEM=R"HTML(<!doctype html><html><head><meta charset=utf-8><meta name=viewport content="width=device-width,initial-scale=1"><title>DeskTV</title><style>
:root{color-scheme:dark;--b:#0b0e12;--p:#141922;--l:#29313d;--t:#edf2f7;--m:#91a0b2;--a:#57d38c}*{box-sizing:border-box}body{margin:0;background:var(--b);color:var(--t);font:14px system-ui;max-width:760px;margin:auto}header{padding:22px 18px 12px}h1{font-size:22px;margin:0}header p{color:var(--m);margin:5px 0}.tabs{display:flex;gap:6px;padding:8px 18px;overflow:auto;position:sticky;top:0;background:var(--b);z-index:2}.tabs button{background:none;border:1px solid var(--l);color:var(--m);padding:8px 11px;border-radius:9px}.tabs button.on{color:var(--t);border-color:var(--a)}main{padding:8px 18px 40px}.tab{display:none}.tab.on{display:block}.card{background:var(--p);border:1px solid var(--l);border-radius:12px;padding:15px;margin:10px 0}h2{font-size:15px;margin:0 0 13px}label{display:block;color:var(--m);margin:11px 0 5px}input,select{width:100%;background:#0d1117;color:var(--t);border:1px solid var(--l);border-radius:8px;padding:10px}.row{display:grid;grid-template-columns:1fr 1fr;gap:10px}.check{display:flex;align-items:center;gap:8px;margin:9px 0}.check input{width:auto}.check label{margin:0}.btn{border:0;border-radius:9px;padding:10px 14px;background:var(--a);color:#07110b;font-weight:700}.ghost{background:#202733;color:var(--t)}small,.muted{color:var(--m)}#msg{position:fixed;bottom:18px;left:50%;transform:translateX(-50%);background:#202733;padding:9px 14px;border-radius:8px;display:none}@media(max-width:520px){.row{grid-template-columns:1fr}}</style></head><body>
<header><h1>DeskTV</h1><p>Weather · network · radar · GitHub</p></header><nav class=tabs><button class=on data-tab=display>Display</button><button data-tab=weather>Weather</button><button data-tab=network>Network</button><button data-tab=radar>Radar</button><button data-tab=github>GitHub</button><button data-tab=system>System</button></nav><main>
<section id=display class="tab on"><div class=card><h2>Screen</h2><label>Mode</label><select id=mode><option value=weather>Ambient weather</option><option value=network>Network guardian</option><option value=radar>Aircraft radar</option><option value=github>GitHub status</option><option value=carousel>Carousel</option></select><label>Carousel dwell (seconds)</label><input id=carouselSec type=number min=5><div class=check><input id=carouselWeather type=checkbox><label>Weather</label></div><div class=check><input id=carouselNetwork type=checkbox><label>Network</label></div><div class=check><input id=carouselRadar type=checkbox><label>Radar</label></div><div class=check><input id=carouselGithub type=checkbox><label>GitHub</label></div><label>Brightness <span id=bv></span>%</label><input id=brightness type=range min=0 max=100 oninput="bv.textContent=value"><label>Rotation</label><select id=rotation><option value=0>0°</option><option value=1>90°</option><option value=2>180°</option><option value=3>270°</option></select></div></section>
<section id=weather class=tab><div class=card><h2>Ambient weather</h2><label>City label</label><input id=wCity><div class=row><div><label>Latitude</label><input id=wLat type=number step=.0001></div><div><label>Longitude</label><input id=wLon type=number step=.0001></div></div><label>Refresh seconds</label><input id=wPoll type=number min=60></div></section>
<section id=network class=tab><div class=card><h2>Network guardian</h2><label>Probe host</label><input id=nHost placeholder=1.1.1.1><div class=row><div><label>Port</label><input id=nPort type=number></div><div><label>Interval seconds</label><input id=nPoll type=number min=2></div></div></div></section>
<section id=radar class=tab><div class=card><h2>Aircraft radar</h2><div class=row><div><label>Latitude</label><input id=rLat type=number step=.0001></div><div><label>Longitude</label><input id=rLon type=number step=.0001></div></div><div class=row><div><label>Range km</label><input id=rRange type=number></div><div><label>Refresh seconds</label><input id=rPoll type=number></div></div><label>Data source</label><select id=rSource><option value=direct>adsb.fi direct</option><option value=webhook>Webhook / proxy</option></select><label>Webhook URL</label><input id=rWebhook><div class=check><input id=rLabels type=checkbox><label>Labels</label></div><div class=check><input id=rVectors type=checkbox><label>Heading vectors</label></div><div class=check><input id=rRim type=checkbox><label>Beyond-range rim targets</label></div></div></section>
<section id=github class=tab><div class=card><h2>GitHub status</h2><label>Repository (owner/name)</label><input id=gRepo placeholder=itsfuad/smalltv-mod><label>Token (optional; blank keeps existing)</label><input id=gToken type=password><label>Refresh seconds</label><input id=gPoll type=number min=60><small>A token increases the API limit. Only repository metadata, commit, issue and PR counts are requested.</small></div></section>
<section id=system class=tab><div class=card><h2>Wi-Fi</h2><label>SSID</label><input id=ssid><label>Password (blank keeps existing)</label><input id=pass type=password><label>Hostname</label><input id=hostname></div><div class=card><h2>Device</h2><div id=status class=muted>Loading…</div><p><button class="btn ghost" onclick=refreshNow()>Refresh screens</button> <button class="btn ghost" onclick=reboot()>Reboot</button></p><label>Firmware .bin</label><input id=fw type=file accept=.bin><p><button class=btn onclick=upload()>Upload firmware</button></p></div></section>
<p><button class=btn onclick=save()>Save settings</button></p></main><div id=msg></div><script>
const $=id=>document.getElementById(id), toast=t=>{msg.textContent=t;msg.style.display='block';setTimeout(()=>msg.style.display='none',2500)};document.querySelectorAll('.tabs button').forEach(b=>b.onclick=()=>{document.querySelectorAll('.tabs button,.tab').forEach(x=>x.classList.remove('on'));b.classList.add('on');$(b.dataset.tab).classList.add('on')});let C;
async function load(){C=await fetch('/api/config').then(r=>r.json());['mode','carouselSec','brightness','rotation','hostname'].forEach(k=>$(k).value=C[k]);bv.textContent=C.brightness;['carouselWeather','carouselNetwork','carouselRadar','carouselGithub'].forEach(k=>$(k).checked=!!C[k]);let w=C.weather||{};wCity.value=w.city||'';wLat.value=w.lat||0;wLon.value=w.lon||0;wPoll.value=w.pollSec||900;let n=C.network||{};nHost.value=n.probeHost||'';nPort.value=n.probePort||443;nPoll.value=n.pollSec||10;let r=C.radar||{};rLat.value=r.lat||0;rLon.value=r.lon||0;rRange.value=r.rangeKm||20;rPoll.value=r.pollSec||10;rSource.value=r.source||'direct';rWebhook.value=r.webhookUrl||'';rLabels.checked=!!r.showLabels;rVectors.checked=!!r.showVectors;rRim.checked=!!r.showRimDots;let g=C.github||{};gRepo.value=(g.repos||[])[0]||'';gPoll.value=g.pollSec||600;ssid.value=(C.wifi&&C.wifi[0]?C.wifi[0].ssid:'');statusLoad()}
async function save(){let body={mode:mode.value,carouselSec:+carouselSec.value,carouselWeather:carouselWeather.checked,carouselNetwork:carouselNetwork.checked,carouselRadar:carouselRadar.checked,carouselGithub:carouselGithub.checked,brightness:+brightness.value,rotation:+rotation.value,hostname:hostname.value,weather:{city:wCity.value,lat:+wLat.value,lon:+wLon.value,pollSec:+wPoll.value},network:{probeHost:nHost.value,probePort:+nPort.value,pollSec:+nPoll.value},radar:{lat:+rLat.value,lon:+rLon.value,rangeKm:+rRange.value,pollSec:+rPoll.value,source:rSource.value,webhookUrl:rWebhook.value,showLabels:rLabels.checked,showVectors:rVectors.checked,showRimDots:rRim.checked},github:{repos:[gRepo.value],token:gToken.value,pollSec:+gPoll.value}};if(ssid.value)body.wifi=[{ssid:ssid.value,pass:pass.value}];let j=await fetch('/api/config',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)}).then(r=>r.json());toast(j.reboot?'Saved; rebooting':'Saved')}
async function statusLoad(){let s=await fetch('/api/status').then(r=>r.json());status.innerHTML=`${s.ssid||'-'} · ${s.ip||'-'}<br>Heap ${s.heap} · RSSI ${s.rssi} dBm<br>${s.fw} ${s.version}`};async function refreshNow(){await fetch('/api/refresh',{method:'POST'});toast('Refreshing')}async function reboot(){await fetch('/api/reboot',{method:'POST'});toast('Rebooting')}function upload(){let f=fw.files[0];if(!f)return toast('Choose a .bin');let d=new FormData;d.append('update',f);fetch('/update',{method:'POST',body:d}).then(r=>toast(r.ok?'Uploaded; rebooting':'Upload failed'))}load();setInterval(statusLoad,10000);
</script></body></html>)HTML";
