#pragma once
#include <Arduino.h>

static const char WEBUI_HTML[] PROGMEM = R"HTML(<!doctype html>
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>DeskMate</title><style>
:root{color-scheme:dark;--bg:#090d13;--panel:#111823;--panel2:#151f2c;--line:#263244;--text:#edf3f8;--muted:#8fa1b5;--accent:#67d6ce;--blue:#76a9fa;--danger:#ff7b82}*{box-sizing:border-box}body{margin:0;background:var(--bg);color:var(--text);font:14px/1.45 system-ui,-apple-system,sans-serif}body:before{content:"";position:fixed;inset:0;pointer-events:none;background:radial-gradient(circle at 70% -20%,#18314355,transparent 45%)}.shell{max-width:760px;margin:auto;position:relative}header{padding:25px 18px 11px}h1{font-size:24px;letter-spacing:-.5px;margin:0}header p{margin:4px 0;color:var(--muted)}nav{display:flex;gap:6px;padding:8px 18px 12px;overflow:auto;position:sticky;top:0;z-index:3;background:#090d13e8;backdrop-filter:blur(10px)}nav button{white-space:nowrap;border:1px solid var(--line);background:#0e151f;color:var(--muted);border-radius:10px;padding:8px 11px}nav button.on{color:var(--text);border-color:var(--accent);background:#102329}main{padding:0 18px 92px}.tab{display:none}.tab.on{display:block}.card{background:linear-gradient(180deg,var(--panel2),var(--panel));border:1px solid var(--line);border-radius:15px;padding:16px;margin:10px 0;box-shadow:0 12px 34px #0003}h2{font-size:15px;margin:0 0 4px}.hint{color:var(--muted);font-size:12px;margin:0 0 13px}label{display:block;color:var(--muted);font-size:12px;margin:12px 0 5px}input,select{width:100%;border:1px solid var(--line);background:#0b111a;color:var(--text);border-radius:9px;padding:10px 11px;outline:none}input:focus,select:focus{border-color:var(--accent)}input[type=range]{padding:0}.grid{display:grid;grid-template-columns:1fr 1fr;gap:10px}.checks{display:grid;grid-template-columns:1fr 1fr;gap:7px;margin-top:11px}.check{display:flex;align-items:center;gap:8px;background:#0c131d;border:1px solid var(--line);padding:9px;border-radius:9px}.check input{width:auto;margin:0}.check label{margin:0;font-size:13px}.actions{display:flex;gap:8px;flex-wrap:wrap}.btn{border:0;border-radius:10px;padding:10px 14px;background:var(--accent);color:#071512;font-weight:750}.btn.secondary{background:#202c3b;color:var(--text)}.btn.danger{background:#3a2027;color:#ffbec2}.savebar{position:fixed;left:0;right:0;bottom:0;padding:12px 18px;background:#090d13e8;border-top:1px solid #1c2634;backdrop-filter:blur(10px);z-index:4}.savebar .btn{width:min(724px,100%);display:block;margin:auto}.status{color:var(--muted);font-family:ui-monospace,monospace;font-size:12px}.secret{display:flex;align-items:center;gap:7px}.dot{width:7px;height:7px;border-radius:50%;background:var(--accent);display:inline-block}.toast{display:none;position:fixed;left:50%;bottom:70px;transform:translateX(-50%);background:#243244;border:1px solid #3b4c61;padding:9px 14px;border-radius:10px;z-index:7;box-shadow:0 8px 30px #0008}@media(max-width:540px){.grid,.checks{grid-template-columns:1fr}}
</style></head><body><div class="shell">
<header><h1>DeskMate</h1><p>Four focused views for a 240 × 240 desk display.</p></header>
<nav><button class="on" data-tab="display">Display</button><button data-tab="weather">Weather</button><button data-tab="network">Network</button><button data-tab="radar">Radar</button><button data-tab="github">GitHub</button><button data-tab="system">System</button></nav><main>
<section id="display" class="tab on"><div class="card"><h2>Screen</h2><p class="hint">Choose one view or rotate selected views.</p><label>Active mode</label><select id="mode"><option value="weather">Weather</option><option value="network">Network guardian</option><option value="radar">Aircraft radar</option><option value="github">GitHub activity</option><option value="carousel">Carousel</option></select><div class="grid"><div><label>Carousel dwell</label><input id="carouselSec" type="number" min="5" max="3600"></div><div><label>Rotation</label><select id="rotation"><option value="0">0°</option><option value="1">90°</option><option value="2">180°</option><option value="3">270°</option></select></div></div><label>Carousel views</label><div class="checks"><div class="check"><input id="carouselWeather" type="checkbox"><label for="carouselWeather">Weather</label></div><div class="check"><input id="carouselNetwork" type="checkbox"><label for="carouselNetwork">Network</label></div><div class="check"><input id="carouselRadar" type="checkbox"><label for="carouselRadar">Radar</label></div><div class="check"><input id="carouselGithub" type="checkbox"><label for="carouselGithub">GitHub</label></div></div><label>Brightness <span id="brightnessValue"></span>%</label><input id="brightness" type="range" min="0" max="100"></div></section>

<section id="weather" class="tab"><div class="card"><h2>OpenWeather</h2><p class="hint">Current conditions and four upcoming 3-hour forecast points. A blank key keeps the saved key.</p><label>API key <span id="weatherKeyState" class="secret"></span></label><input id="weatherKey" type="password" autocomplete="off" placeholder="e.g. 78bd9cea4f…59197…"><div class="grid"><div><label>Location label</label><input id="weatherCity" placeholder="Dhaka"></div><div><label>Units</label><select id="weatherMetric"><option value="1">Metric · °C</option><option value="0">Imperial · °F</option></select></div></div><div class="grid"><div><label>Latitude</label><input id="weatherLat" type="number" step=".00001"></div><div><label>Longitude</label><input id="weatherLon" type="number" step=".00001"></div></div><label>Refresh interval (seconds)</label><input id="weatherPoll" type="number" min="300" max="3600"></div></section>

<section id="network" class="tab"><div class="card"><h2>Network guardian</h2><p class="hint">Measures internet TCP latency, DNS resolution, availability, Wi-Fi quality and outages.</p><div class="grid"><div><label>Internet probe host</label><input id="networkHost" placeholder="1.1.1.1"></div><div><label>TCP port</label><input id="networkPort" type="number" min="1" max="65535"></div></div><label>DNS test hostname</label><input id="networkDns" placeholder="github.com"><label>Probe interval (seconds)</label><input id="networkPoll" type="number" min="3" max="300"></div></section>

<section id="radar" class="tab"><div class="card"><h2>Aircraft radar</h2><p class="hint">Static full-screen PPI scope. Aircraft silhouettes scale from ADS-B emitter category when available; the screen redraws only when data changes.</p><div class="grid"><div><label>Home latitude</label><input id="radarLat" type="number" step=".00001"></div><div><label>Home longitude</label><input id="radarLon" type="number" step=".00001"></div></div><div class="grid"><div><label>Range (km)</label><input id="radarRange" type="number" min="1" max="500"></div><div><label>Refresh (seconds)</label><input id="radarPoll" type="number" min="3"></div></div><div class="grid"><div><label>Data source</label><select id="radarSource"><option value="direct">adsb.fi direct</option><option value="webhook">Webhook / proxy</option></select></div><div><label>Marker scale</label><select id="radarScale"><option value="0">Compact</option><option value="1">Balanced</option><option value="2">Large</option></select></div></div><label>Webhook URL</label><input id="radarWebhook" placeholder="http://192.168.1.10/aircraft"><div class="grid"><div><label>Minimum altitude (ft)</label><input id="radarMinAlt" type="number" min="0" max="60000"></div><div><label>Distance units</label><select id="radarMiles"><option value="0">Kilometres</option><option value="1">Miles</option></select></div></div><div class="checks"><div class="check"><input id="radarLabels" type="checkbox"><label for="radarLabels">Labels</label></div><div class="check"><input id="radarVectors" type="checkbox"><label for="radarVectors">Vectors</label></div><div class="check"><input id="radarRim" type="checkbox"><label for="radarRim">Rim targets</label></div></div></div></section>

<section id="github" class="tab"><div class="card"><h2>GitHub user activity</h2><p class="hint">Uses the authenticated user from the token. Shows current-year commits, open issues, open pull requests, streak and a memory-safe 52-week contribution graph.</p><label>Personal access token <span id="githubKeyState" class="secret"></span></label><input id="githubToken" type="password" autocomplete="off" placeholder="github_pat_… or ghp_…"><label>Refresh interval (seconds)</label><input id="githubPoll" type="number" min="300" max="3600"><p class="hint">A classic token with read:user can include private contribution counts; public activity works with a valid user token. The token stays in the device configuration.</p></div></section>

<section id="system" class="tab"><div class="card"><h2>Wi-Fi and identity</h2><label>SSID</label><input id="ssid"><label>Password</label><input id="password" type="password" placeholder="Blank keeps the saved password"><label>Hostname</label><input id="hostname"></div><div class="card"><h2>Device</h2><div id="status" class="status">Loading…</div><div class="actions" style="margin-top:14px"><button class="btn secondary" id="refreshButton">Refresh data</button><button class="btn secondary" id="rebootButton">Reboot</button></div><label>OTA firmware (.bin)</label><input id="firmware" type="file" accept=".bin"><div class="actions" style="margin-top:10px"><button class="btn" id="uploadButton">Upload firmware</button></div></div></section>
</main></div><div class="savebar"><button class="btn" id="saveButton">Save settings</button></div><div id="toast" class="toast"></div>
<script>
const q=id=>document.getElementById(id);let config={};
function toast(text){const el=q('toast');el.textContent=text;el.style.display='block';clearTimeout(toast.timer);toast.timer=setTimeout(()=>el.style.display='none',2600)}
function secretState(id,set){q(id).innerHTML=set?'<span class="dot"></span> configured':''}
document.querySelectorAll('nav button').forEach(button=>button.onclick=()=>{document.querySelectorAll('nav button,.tab').forEach(el=>el.classList.remove('on'));button.classList.add('on');q(button.dataset.tab).classList.add('on')});
q('brightness').oninput=()=>q('brightnessValue').textContent=q('brightness').value;
async function getJson(url,options){const response=await fetch(url,options);if(!response.ok)throw new Error(await response.text()||response.status);return response.json()}
async function load(){try{config=await getJson('/api/config');['mode','carouselSec','rotation','hostname'].forEach(id=>q(id).value=config[id]??'');q('brightness').value=config.brightness??90;q('brightnessValue').textContent=q('brightness').value;['carouselWeather','carouselNetwork','carouselRadar','carouselGithub'].forEach(id=>q(id).checked=!!config[id]);const w=config.weather||{};q('weatherCity').value=w.city||'';q('weatherLat').value=w.lat??0;q('weatherLon').value=w.lon??0;q('weatherMetric').value=w.metric===false?'0':'1';q('weatherPoll').value=w.pollSec||600;secretState('weatherKeyState',w.apiKeySet);const n=config.network||{};q('networkHost').value=n.probeHost||'1.1.1.1';q('networkPort').value=n.probePort||443;q('networkDns').value=n.dnsHost||'github.com';q('networkPoll').value=n.pollSec||10;const r=config.radar||{};q('radarLat').value=r.lat??0;q('radarLon').value=r.lon??0;q('radarRange').value=r.rangeKm||20;q('radarPoll').value=r.pollSec||10;q('radarSource').value=r.source||'direct';q('radarWebhook').value=r.webhookUrl||'';q('radarScale').value=r.uiScale??1;q('radarMinAlt').value=r.minAltFt||0;q('radarMiles').value=r.unitsMi?'1':'0';q('radarLabels').checked=!!r.showLabels;q('radarVectors').checked=!!r.showVectors;q('radarRim').checked=!!r.showRimDots;const g=config.github||{};q('githubPoll').value=g.pollSec||900;secretState('githubKeyState',g.tokenSet);q('ssid').value=config.wifi?.[0]?.ssid||'';await loadStatus()}catch(error){toast('Load failed: '+error.message)}}
async function save(){const body={mode:q('mode').value,carouselSec:+q('carouselSec').value,carouselWeather:q('carouselWeather').checked,carouselNetwork:q('carouselNetwork').checked,carouselRadar:q('carouselRadar').checked,carouselGithub:q('carouselGithub').checked,rotation:+q('rotation').value,brightness:+q('brightness').value,hostname:q('hostname').value,weather:{apiKey:q('weatherKey').value,city:q('weatherCity').value,lat:+q('weatherLat').value,lon:+q('weatherLon').value,metric:q('weatherMetric').value==='1',pollSec:+q('weatherPoll').value},network:{probeHost:q('networkHost').value,probePort:+q('networkPort').value,dnsHost:q('networkDns').value,pollSec:+q('networkPoll').value},radar:{lat:+q('radarLat').value,lon:+q('radarLon').value,rangeKm:+q('radarRange').value,pollSec:+q('radarPoll').value,source:q('radarSource').value,webhookUrl:q('radarWebhook').value,uiScale:+q('radarScale').value,minAltFt:+q('radarMinAlt').value,unitsMi:q('radarMiles').value==='1',showLabels:q('radarLabels').checked,showVectors:q('radarVectors').checked,showRimDots:q('radarRim').checked},github:{token:q('githubToken').value,pollSec:+q('githubPoll').value}};if(q('ssid').value)body.wifi=[{ssid:q('ssid').value,pass:q('password').value}];try{const result=await getJson('/api/config',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});toast(result.reboot?'Saved · rebooting':'Saved');if(!result.reboot)setTimeout(load,700)}catch(error){toast('Save failed: '+error.message)}}
async function loadStatus(){try{const s=await getJson('/api/status');q('status').innerHTML=`${s.fw} ${s.version}<br>${s.ssid||'not connected'} · ${s.ip||'-'} · ${s.rssi} dBm<br>heap ${s.heap} · max block ${s.maxblk}<br>uptime ${s.uptime}s · ${s.reset||'-'}` }catch(error){q('status').textContent='Status unavailable'}}
q('saveButton').onclick=save;q('refreshButton').onclick=async()=>{await fetch('/api/refresh',{method:'POST'});toast('Data refresh requested')};q('rebootButton').onclick=async()=>{await fetch('/api/reboot',{method:'POST'});toast('Rebooting')};q('uploadButton').onclick=async()=>{const file=q('firmware').files[0];if(!file)return toast('Choose a firmware .bin');const data=new FormData;data.append('update',file);const response=await fetch('/update',{method:'POST',body:data});toast(response.ok?'Uploaded · rebooting':'Upload failed')};
load();setInterval(loadStatus,10000);
</script></body></html>)HTML";
