name: build
on: [push, pull_request, workflow_dispatch]
jobs:
  esp8266:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: {python-version: '3.x'}
      - run: pip install platformio
      - run: pio run -e deskmate
      - uses: actions/upload-artifact@v4
        with:
          name: deskmate-esp8266-firmware
          path: .pio/build/deskmate/firmware.bin
